### PR TITLE
feat: Add support for 3d assets through assimp converter

### PR DESCRIPTION
**Pull request by Aymendje**
This is a start for #144
It does not support all the 3d formats, but its a good few

### CODE REVIEW

**Comment by C4illin** [comment]
Rename your commit to start with "feat:" just so the automation picks it up

**Comment by C4illin** [comment]
Sorry you have to rename the commit message and not just the title. I can try to do it for you

**Comment by Aymendje** [comment]
oh sorry was not aware of that, good to know for next time, thank you !

**Comment by C4illin** [comment]
No worries! And thank you so much for your PRs. This project uses [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) quite nice when it works, bit this is the first time using it for me

**Pull request merged**
