### PR TITLE
Add search bar for formats

### PR DESCRIPTION
**Pull request by luis-c465**
## Summary

Have been really enjoying using this tool, and wanted to contribute back.

This pull request completes the `Add searchable list of formats` from the Todos in the readme

## Details

- Adds a searchable list of formats above the format selection on the convert page
- Clicking on the search bar will focus the input and show a popup of all available conversions grouped by the converter used.
- Typing in the search bar filters the popup for matching conversions
- Clicking anywhere other than the search bar or popup closes the popup
- Clicking on a conversion on the popup closes the popup and updates the conversion in the select box

Feel free to let me know if it doesn't line up with what you were thinking for the searchable list, so I can improve it :)

## Images

image

image

image

image

### CODE REVIEW

**Comment by C4illin** [comment]
Sorry for not reviewing this yet will look it through soon. The design looks awesome!

**Comment by C4illin** [comment]
Some minor things:
- Remove the old dropdown menu entirely, two fields is just confusing.
- Rename the commit to follow conventional commits eg. "feat: Add search bar for formats"
- The popup is very small on mobile, I think it could be made larger.

**Comment by luis-c465** [comment]
Mobile Image

# Made the following changes

- Hid the old dropdown from the UI as to not be confusing and made the search bar show the currently selected format
- Renamed the commit to follow conventional commits
- Added CSS making the popup larger on small / mobile screens
- Made the search case-insensitive as it made searching on mobile frustrating
- Fixed an issue on Safari / iPhone browsers where the format popup buttons would not function

**Comment by C4illin** [comment]
Very nice! I am missing an indication of what format I have selected
image
Here it should in some way show what format I will convert to. Maybe adding a text below the search bar or replacing the search query with the selected value?

**Comment by C4illin** [comment]
Ohh what that does look perfect. Weird that it doesn't work here, tested multiple browsers with both local and docker :(

**Comment by luis-c465** [comment]
Had a friend try it out and turned out that only fast clicks (under `<100ms`) would count for clicking on the format button in the popup. 

Made a commit, which should fix it by using `onmousedown` instead of `onclick`.

Let me know if it works now :)

**Comment by C4illin** [comment]
It doesn't work unfortunately. And don't we want onclick so that it also registers touch events and keyboard navigation?

**Comment by C4illin** [comment]
Wait now it actually works!

**Comment by C4illin** [comment]
And it also works with onclick

**Comment by luis-c465** [comment]
> [...] and don't we want onclick so that it also registers touch events and keyboard navigation?

Testing it on an iPhone and clicking the buttons works as expected. 

Unfortunately, the popup as a whole does not support keyboard navigation. Because clicking `tab` and focusing any other element on the screen closes the popup :(

**Comment by C4illin** [comment]
> Testing it on an iPhone and clicking the buttons works as expected.

Then it is all good! I thought it worked the same way as event listeners do

> Unfortunately, the popup as a whole does not support keyboard navigation. Because clicking `tab` and focusing any other element on the screen closes the popup :(

In that case I think you need to .focus the element so that the keyboard nav starts there. But it isn't that important, so we can skip it for now

**Review by C4illin — APPROVED** [review]

**Pull request merged**
