### PR TITLE
fix: resize to fit for ico

### PR DESCRIPTION
**Pull request by C4illin**
issue #157

### CODE REVIEW

**Comment by C4illin** [comment]
looks good @Aymendje ?

**Comment by Aymendje** [comment]
LGTM

**Comment by Aymendje** [comment]
We might want to add a message telling the user the icon will be resized to 256 as it is a limitation of the format

**Comment by C4illin** [comment]
> We might want to add a message telling the user the icon will be resized to 256 as it is a limitation of the format

Great idea!

**Pull request merged**
